# Fast Strategy - 追求速度和最低成本
# 适用场景：快速原型验证、大批量处理、对质量要求不高的场景

strategy:
  name: "fast"
  display_name: "Fast Processing"
  description: "优先速度和成本，适合快速处理大量文档"
  
# PDF 输入配置
pdf:
  start_page: 0
  end_page: null

# 解析配置 - 最简化
parsing:
  extract_tables: false
  extract_images: false
  table_strategy: "text"

# 规范化配置 - 基础清洗
normalization:
  remove_headers_footers: true
  merge_broken_lines: true
  normalize_whitespace: true
  normalize_punctuation: false
  header_footer_max_lines: 2
  min_line_length: 10

# 切片配置 - 大 chunk，减少数量
chunk:
  size: 1200
  overlap: 100
  min_chunk_size: 200
  split_by: "token"
  respect_sentence_boundary: false

# 质量校验 - 宽松标准
quality:
  min_length: 100
  max_noise_ratio: 0.5
  min_info_density: 0.2
  max_repetition_ratio: 0.7
  
  garble_detection:
    enabled: true
    max_garble_ratio: 0.2
  
  llm_validation:
    enabled: false
    only_edge_chunks: false
    edge_threshold: 0.5

# LLM 配置 - 关闭
llm:
  enabled: false
  provider: "ollama"
  model: "qwen:7b"
  endpoint: "http://localhost:11434"
  max_calls: 0
  timeout: 30
  retry_times: 1
  temperature: 0.1

# 输出配置
output:
  dir: "data/output"
  pages_file: "pages.jsonl"
  chunks_file: "chunks.jsonl"
  rejected_file: "rejected.jsonl"
  stats_file: "stats.json"
  checkpoint_file: "checkpoint.json"

# 运行配置
runtime:
  batch_size: 20
  log_level: "WARNING"
  save_interval: 100
  enable_checkpoint: true
